### ISSUE TITLE
GNU/Linux x86_64: compiling fails

### ISSUE THREAD

**Issue by darealshinji** [fr1tz/terminal-overload#66]
I've tried to compile the release version 0.6.0 from source, but it fails to link the binary.
Here's the output with all the errors: https://gist.github.com/darealshinji/688c2f9d17f6ea2fc580
I'm using Ubuntu 14.04 64 bit.

**Comment by fr1tz** [comment]
Oops, forgot to commit the quick'n'dirty "fix" for this. Remedied: https://github.com/fr1tz/terminal-overload/commit/63b6514de6a9d532011fe4dfb71482bdb35ad9bf

**Comment by darealshinji** [comment]
It works now.
