### ISSUE TITLE
Terminal Overload on torque3d.org

### ISSUE THREAD

**Issue by eightyeight** [fr1tz/terminal-overload#68]
Hey @fr1tz, would you mind if we added TOL banners to T3D's official home at [torque3d.org](http://torque3d.org)? We'd use [these two](https://github.com/eightyeight/Torque3DLandingPage/commit/0e2244786c0ff3c7f272195ca45eed74a7b95a83) banners (committed, but not to the production site). It's hard to capture the game's look and feel in still images, but I thought these two were moderately representative of what you've managed to achieve. We'd also like to talk in the future about maybe adding TOL to the games page properly :).

**Comment by fr1tz** [comment]
Cool. No objections from my side.
